name: main

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  gh-release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          persist-credentials: false
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: "16.x"
      - uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}
      - name: Release to GitHub Pages
        env:
          USE_SSH: true
          GIT_USER: git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "gh-actions"
          yarn install
          yarn build
          yarn export
          yarn deploy
